
const CONFIG = {
  SCENE_WIDTH: 320,
  SCENE_HEIGHT: 240,

  CLERIC_HEAL: 5,
  CLERIC_MAX_HEALTH: 24,
  CLERIC_INITIATIVE: 10,
  CLERIC_BASE_ATTACK: 8,
  CLERIC_BASE_DEFENSE: 5,

  KNIGHT_BASE_ATTACK: 10,
  KNIGHT_BASE_DEFENSE: 6,
  KNIGHT_BASE_INITIATIVE: 8,
  KNIGHT_BASE_MAX_HEALTH: 30,
  KNIGHT_BASE_BLOCK: 10,

  ROGUE_BASE_ATTACK: 15,
  ROGUE_BASE_DEFENSE: 3,
  ROGUE_BASE_INITIATIVE: 12,
  ROGUE_BASE_MAX_HEALTH: 22,
  ROGUE_COUNTER: false,

  MUSH_MAX_HEALTH: 10,
  MUSH_INITIATIVE: 5,
  MUSH_BASE_ATTACK: 5,
  MUSH_BASE_DEFENSE: 5,
  MUSH_MODE: 0
}

export default CONFIG
